### ISSUE TITLE
Ability to show resistance level

### ISSUE THREAD

**Issue by lanes100** [TrackMyIndoorWorkout/TrackMyIndoorWorkout#458] opened 2023-09-03 01:02 UTC
Hi, I'm new to this app, but I'm trying to figure out a way to display the resistance being read on the app from my bike. I want to see this so I can use the app for doing peloton rides, and my bike has a 100 step resistance so I wanted to see how I can add this. When I go to the battery & extras page on the bottom right, it says the features are cadence, total distance, resistance level, expended energy, elapsed time, and power measurement, but on the workout screen all i can see is my output, speed, and cadence. I'd love a way to add the resistance level the bike is showing being read by the app if that's possible.

**Comment by MrCsabaToth** [comment] 2023-09-03 20:49
The app doesn't have this capability right now to display the resistance level. Duplicate #337 #187

I looked for "resistance level" in the app and on the website but I don't see it mentioned like you quote. I guess you are talking about your bike's console or your bike's manual? What kind of bike do you have BTW?

If it's an FTMS bike then Indoor Bike standard has a place for resistance level https://github.com/oesmith/gatt-xml/blob/4fd2ede1d3da9365fdc6dec89290c346581a03f9/org.bluetooth.characteristic.indoor_bike_data.xml#L142, however it depends on the actual console if it transmits that data or not https://github.com/oesmith/gatt-xml/blob/4fd2ede1d3da9365fdc6dec89290c346581a03f9/org.bluetooth.characteristic.indoor_bike_data.xml#L49

As opposed to what steps I describe in #337, the easiest would be if we wouldn't persist the resistance level data, then we wouldn't have to deal with exporting it either or all the shenanigans. So if it's only for display purposes during the workout that would require less development.

Since the order of the metrics is not configurable right now (#179), where would you want to see the resistance level metric on the screen (between which current measurements?).

**Comment by MrCsabaToth** [comment] 2023-09-03 20:50
This ticket would cover Indoor Bikes with the first MVP. Maybe we can cover other sports if their FTMS protocol also has resistance level.

**Comment by MrCsabaToth** [comment] 2023-09-03 20:59
Regarding our codebase, one of the key places are: https://github.com/TrackMyIndoorWorkout/TrackMyIndoorWorkout/blob/9720aebe2de3788fe0934f6200b167d5d101892c/lib/devices/device_descriptors/indoor_bike_device_descriptor.dart#L55

**Comment by MrCsabaToth** [comment] 2023-09-07 17:37
Hey @lanes100, where would you want the resistance level displayed during workout in order? Current order is: Time, Calories, Power, Speed / pace, RPM / SPM, HR, Distance.
I put down some foundations and I believe I just need to display it now along with a preferences settings which would enable it.

**Comment by MrCsabaToth** [comment] 2024-02-16 16:33
The core data capture code is there, we only need to display it now

**Comment by MrCsabaToth** [comment] 2024-02-27 22:45
Duplicate of #337

**Closed by MrCsabaToth** 2024-02-27 22:45 UTC
Labels: enhancement

**Comment by MrCsabaToth** [comment] 2024-04-29 06:03
Releasing this with beta 155 (in some hours hopefully when it passes Google checks and scrunity), the resistance level can be turned on for display in the preferences.

**Comment by MrCsabaToth** [comment] 2024-05-07 19:41
@lanes100 Were you able to test this with the beta by any chance?

**Comment by MrCsabaToth** [comment] 2024-05-07 19:45
![Screenshot_20240507-124215](https://github.com/TrackMyIndoorWorkout/TrackMyIndoorWorkout/assets/744949/89a5e967-2313-4ca6-8af5-87409fcc4330)
